# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net60&pivots=development-environment-vscode
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and DOTNET_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Build and deploy TaskProject ASP.Net Core API to an Azure API App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_APIAPP_NAME: TaskManagementProject
  PACKAGE_NAME: TaskProjects.Api/publish
  BUILD_CONFIG: Release
  DOTNET_VERSION: 8.0.X
  WORKING_DIRECTORY: TaskProjects.Api


jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: üõí Checkout del codigo
        uses: actions/checkout@v4

      - name: üîß Configurar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: üèóÔ∏è Restore dependencies
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: üî® Build Project
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.BUILD_CONFIG }} --no-restore

      - name: ‚úÖ Run Unit Test
        run: dotnet test "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.BUILD_CONFIG }} --no-build --no-restore

      - name: üõ´ Generate Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" -c ${{ env.BUILD_CONFIG }} -o "${{ env.PACKAGE_NAME }}" --no-build --no-restore

      - name: üóúÔ∏è Generar archivo .zip
        run: |
         cd "${{ env.PACKAGE_NAME }}"
         zip -r ./QuePutas.zip .

      - name: üí© Merida
        run: ls ${{ github.workspace }}/TaskProjects.Api

      - name: üîç Verificar existencia del archivo ZIP
        run: |
         echo "üìÇ Directorio actual: $(pwd)"
         echo "üìÇ Otro actual: ${{ github.workspace }}"
         echo "üìÇ Otro actual: ${{ github.workspace }}/TaskProjects.Api"
         ls -lah  # Muestra los archivos en el directorio actual
         if [ -f "deploy.zip" ]; then
         echo "‚úÖ deploy.zip encontrado."
         else
         echo "‚ùå ERROR: deploy.zip no se gener√≥ correctamente."
         exit 1
         fi
          
      - name: ‚¨ÜÔ∏è Upload the zip in artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: QuePutas.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: main
    
    steps:
    
      - name: ‚¨áÔ∏è Download artifact from buil job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          
      - name: üöÄ Deploy in Azure API App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APIAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_TP_APIAPP_PUBLISH_PROFILE }}
          package: QuePutas.zip
  
